"""Add pipeline stages

Revision ID: 0d6e471a625c
Revises: c7f4a1b2d3e4
Create Date: 2026-07-13 15:55:27.938859
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6e471a625c'
down_revision: Union[str, None] = 'c7f4a1b2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_stages',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_workspace_id'), 'pipeline_stages', ['workspace_id'], unique=False)
    op.add_column('people', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'people', 'pipeline_stages', ['stage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'stage_id')
    op.drop_index(op.f('ix_pipeline_stages_workspace_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    # ### end Alembic commands ###
