"""Add Person relationship strength fields

Revision ID: 21b4fddbb1cb
Revises: 52471928e0a4
Create Date: 2026-07-14 00:07:10.272771
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b4fddbb1cb'
down_revision: Union[str, None] = '52471928e0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('manual_warmth', sa.BigInteger(), nullable=True))
    op.add_column('people', sa.Column('calculated_freshness', sa.BigInteger(), nullable=True))
    op.add_column('people', sa.Column('last_engaged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'last_engaged_at')
    op.drop_column('people', 'calculated_freshness')
    op.drop_column('people', 'manual_warmth')
    # ### end Alembic commands ###
