"""Add person_merges table

Revision ID: 2defeb53c8de
Revises: f1ff6274bf36
Create Date: 2026-07-13 01:56:23.818519
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2defeb53c8de"
down_revision: Union[str, None] = "f1ff6274bf36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_merges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("target_person_id", sa.UUID(), nullable=False),
        sa.Column("source_person_id", sa.Uuid(), nullable=False),
        sa.Column("merged_by_user_id", sa.UUID(), nullable=False),
        sa.Column("merge_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["merged_by_user_id"], ["app_users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["target_person_id"], ["people.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_person_merges_source_person_id"),
        "person_merges",
        ["source_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_person_merges_target_person_id"),
        "person_merges",
        ["target_person_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_person_merges_workspace_id"), "person_merges", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_person_merges_workspace_id"), table_name="person_merges")
    op.drop_index(op.f("ix_person_merges_target_person_id"), table_name="person_merges")
    op.drop_index(op.f("ix_person_merges_source_person_id"), table_name="person_merges")
    op.drop_table("person_merges")
    # ### end Alembic commands ###
