"""Add Activity pin, soft delete and Attachment model

Revision ID: 52471928e0a4
Revises: 1ba82aea6ad2
Create Date: 2026-07-14 00:04:26.055902
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52471928e0a4"
down_revision: Union[str, None] = "1ba82aea6ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachments",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachments_activity_id"), "attachments", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_attachments_workspace_id"), "attachments", ["workspace_id"], unique=False
    )
    op.add_column(
        "activities", sa.Column("is_pinned", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("activities", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("activities", "deleted_at")
    op.drop_column("activities", "is_pinned")
    op.drop_index(op.f("ix_attachments_workspace_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_activity_id"), table_name="attachments")
    op.drop_table("attachments")
    # ### end Alembic commands ###
