"""add background_jobs table

Revision ID: 6bfc5792fd2d
Revises: 69dd014798af
Create Date: 2026-07-13 11:40:14.049516
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bfc5792fd2d'
down_revision: Union[str, None] = '69dd014798af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_workspace_id'), 'background_jobs', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_import_batches_workspace_created'), table_name='import_batches')
    op.drop_index(op.f('ix_message_templates_workspace_name'), table_name='message_templates', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('people', 'next_action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_people_next_action_date'), table_name='people')
    op.drop_index(op.f('ix_people_priority'), table_name='people')
    op.drop_index(op.f('ix_people_stage'), table_name='people')
    op.drop_index(op.f('ix_people_status'), table_name='people')
    op.drop_index(op.f('ix_people_workspace_favorite'), table_name='people')
    op.drop_index(op.f('ix_people_workspace_url'), table_name='people', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('user_settings', 'settings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_workspace_members_workspace_user'), table_name='workspace_members', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workspace_members_workspace_user'), 'workspace_members', ['workspace_id', 'user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('user_settings', 'settings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_people_workspace_url'), 'people', ['workspace_id', 'linkedin_url'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_people_workspace_favorite'), 'people', ['workspace_id', 'is_favorite'], unique=False)
    op.create_index(op.f('ix_people_status'), 'people', ['status'], unique=False)
    op.create_index(op.f('ix_people_stage'), 'people', ['stage'], unique=False)
    op.create_index(op.f('ix_people_priority'), 'people', ['priority'], unique=False)
    op.create_index(op.f('ix_people_next_action_date'), 'people', ['next_action_date'], unique=False)
    op.alter_column('people', 'next_action_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_message_templates_workspace_name'), 'message_templates', ['workspace_id', 'name'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_import_batches_workspace_created'), 'import_batches', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.drop_index(op.f('ix_background_jobs_workspace_id'), table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
