"""phase_3_analytics_and_invites

Revision ID: d6d2768c3e76
Revises: 21b4fddbb1cb
Create Date: 2026-07-14 00:59:24.975725
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6d2768c3e76"
down_revision: Union[str, None] = "21b4fddbb1cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_invites",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name="fk_workspace_invites_workspace_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workspace_invites_email"), "workspace_invites", ["email"], unique=False
    )
    op.create_index(op.f("ix_workspace_invites_token"), "workspace_invites", ["token"], unique=True)
    op.create_index(
        op.f("ix_workspace_invites_workspace_id"),
        "workspace_invites",
        ["workspace_id"],
        unique=False,
    )
    op.add_column("activities", sa.Column("template_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_activities_template_id",
        "activities",
        "message_templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "workspace_members",
        sa.Column(
            "dashboard_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "workspace_members",
        sa.Column("weekly_outreach_target", sa.Integer(), server_default="50", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace_members", "weekly_outreach_target")
    op.drop_column("workspace_members", "dashboard_config")
    op.drop_constraint("fk_activities_template_id", "activities", type_="foreignkey")
    op.drop_column("activities", "template_id")
    op.drop_index(op.f("ix_workspace_invites_workspace_id"), table_name="workspace_invites")
    op.drop_index(op.f("ix_workspace_invites_token"), table_name="workspace_invites")
    op.drop_index(op.f("ix_workspace_invites_email"), table_name="workspace_invites")
    op.drop_table("workspace_invites")
    # ### end Alembic commands ###
