"""Add saved people views

Revision ID: f1ff6274bf36
Revises: 005_people_favorites
Create Date: 2026-07-12 22:32:55.814502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ff6274bf36'
down_revision: Union[str, None] = '005_people_favorites'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_people_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('sort_by', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_people_views_user_id'), 'saved_people_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_people_views_workspace_id'), 'saved_people_views', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_people_views_workspace_id'), table_name='saved_people_views')
    op.drop_index(op.f('ix_saved_people_views_user_id'), table_name='saved_people_views')
    op.drop_table('saved_people_views')
    # ### end Alembic commands ###
